# Generated by Django 2.1.4 on 2019-01-28 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('a', 'Active'), ('b', 'Booked')], default='a', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('place', models.IntegerField()),
                ('adate', models.DateField(blank=True, default=datetime.date.today)),
                ('ddate', models.DateField(blank=True, default=datetime.date.today)),
                ('atime', models.CharField(max_length=6)),
                ('dtime', models.CharField(max_length=6)),
                ('arpoint', models.CharField(blank=True, choices=[('Moscow', 'm'), ('Saint-Petersburg', 'spb'), ('Kazan', 'k'), ('Perm', 'p'), ('Astana', 'a'), ('Vladivostok', 'v'), ('Surgut', 's'), ('Saratov', 's'), ('Tashkent', 't'), ('Kirov', 'k')], default='Moscow', max_length=20)),
                ('dpoint', models.CharField(blank=True, choices=[('Moscow', 'm'), ('Saint-Petersburg', 'spb'), ('Kazan', 'k'), ('Perm', 'p'), ('Astana', 'a'), ('Vladivostok', 'v'), ('Surgut', 's'), ('Saratov', 's'), ('Tashkent', 't'), ('Kirov', 'k')], default='Saint-Petersburg', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Ticket'),
        ),
    ]
