# Generated by Django 2.1.4 on 2019-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190130_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'a'), ('Booked', 'b')], default='a', max_length=1),
        ),
    ]
